- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Start Nginx
  service:
    name: nginx
    state: started

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Python module
  pip:
    name: docker
    state: present

- name: Copy application files
  copy:
    src: ../app/
    dest: /home/your_user/app/

- name: Build the Docker image
  command: docker build -t flask-app /home/your_user/app/

- name: Run the Docker container
  command: docker run -d -p 80:5000 flask-app

